[workspace]
resolver = "2"
members = [
    "exe",
    "core",
]

[profile.release]
lto = true
strip = true
panic = "abort"

[profile.debug_with_release]
inherits = "release"
debug = true
strip = false
