[package]
name = "rlbot_sockets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
flatbuffers = { git = "https://github.com/google/flatbuffers", branch = "master" }
