[match]
game_mode = "Soccer"
game_map_upk = "Stadium_P"

[[cars]]
config = "../../../python-interface/tests/atba/atba.bot.toml"
team = 0

[[cars]]
config = "../../../python-interface/tests/atba/atba.bot.toml"
team = 0

[[cars]]
config = "../../../python-interface/tests/atba/atba.bot.toml"
team = 0

[[cars]]
config = "../../../python-interface/tests/atba/atba.bot.toml"
team = 1

[[cars]]
config = "../../../python-interface/tests/atba/atba.bot.toml"
team = 1

[[cars]]
config = "../../../python-interface/tests/atba/atba.bot.toml"
team = 1
