[rlbot]
auto_start_bots = true

[match]
num_cars = 6
game_mode = "Soccer"
game_map_upk = "Stadium_P"

[[cars]]
config = "../../../python-interface/tests/atba/atba.toml"
team = 0

[[cars]]
config = "../../../python-interface/tests/atba/atba.toml"
team = 0

[[cars]]
config = "../../../python-interface/tests/atba/atba.toml"
team = 0

[[cars]]
config = "../../../python-interface/tests/atba/atba.toml"
team = 1

[[cars]]
config = "../../../python-interface/tests/atba/atba.toml"
team = 1

[[cars]]
config = "../../../python-interface/tests/atba/atba.toml"
team = 1
