[package]
name = "rlbot_sim"
version.workspace = true
edition.workspace = true
license-file.workspace = true
description = "A backend for RLBotServer running RocketSim"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocketsim = { git = "https://github.com/ZealanL/RocketSim.git", branch = "v3-rust" }
rlbot_flat = { git = "https://github.com/RLBot/rust-interface.git", rev = "80aa06a" }
tokio = { version = "1.36.0", features = ["macros", "rt", "net", "io-util"] }
thiserror = "2.0.3"
async-timer = { version = "1.0.0-beta.15", features = ["tokio1"] }
clap = { version = "4.5.27", features = ["color", "derive"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
# pedantic = "warn"
# nursery = "warn"
