[package]
name = "rlbot_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "23.5.26"
glam = "0.24.1"
rocketsim_rs = { version = "0.18.0", features = ["bin"] }
tokio = { version = "1.32.0", features = ["macros", "rt", "rt-multi-thread", "sync", "net", "io-util", "time"] }
