[package]
name = "rlbot_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocketsim_rs = "0.23.0"
tokio = { version = "1.35.0", features = ["macros", "rt", "rt-multi-thread", "sync", "net", "io-util", "time"] }
rlbot_core_types = { path = "../core" }
